import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full h-[5vh] bg-gray-500 flex items-center justify-center">
          <h1 className="mt-5 text-5xl text-white">* * *</h1>
        </div>
        <div className="w-full h-[10vh] bg-white flex items-center justify-center">
          <h1 className="text-3xl font-bold">Todo List</h1>
        </div>
        <div className="w-full h-[100vh] bg-gray-100 flex">
          {children}
        </div>
        
      </body>
      <footer className="w-full h-[10vh] bg-gray-400 flex items-center justify-center">
        <h2 className="text-xl">Bài test Todo list của Hoàng Phi</h2>
      </footer>
    </html>
  );
}
